language: php
php:
  - 5.5
  - 5.6
  - hhvm
  - nightly

install: php vendor/vendors.php

before_script:
    - composer self-update
    - composer install

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
  fast_finish: true